/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RandomNumber_Captcha_otp_gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
